### Numpy
    Numeric Python의 약자
    수학분야 관련 통계 연산작업시 사용
    과학 계산 컴퓨팅, 데이타 분석에 필요한 기본적인 패키지
    
    Numpy배열은 리스트와 거의 흡사
    리스트보다 훨씬 빠르고 메모리 효율성이 높아서 성능상 우의를 차지한다.
        
    Numpy는 가장 기본이 되는 패키지로,   
    바로 다음으로 배우게 될 Pandas는 Numpy를 기반으로 만들어졌다
    
    Numpy는 사용에 앞서서 import 해서 사용해야 한다.
    Numpy 배열 만드는 방법
    1) array() 사용
    2) random 모듈의 랜덤함수 사용

#### Numpy 버전 체크

In [4]:
import numpy as np

np.__version__

np.__name__

'numpy'

### 1. np 배열 생성 | 리스트와 비교
    array() 함수 사용 | rand() 함수 사용

#### array 함수

In [23]:
a = [1,2,3,4]
b = [4,5,6,7]
numpy_a = np.array(a)
numpy_b = np.array(b)
summ = a + b
print(summ)
print(numpy_a)
print(numpy_b)
print('='* 40)
sum = numpy_a + numpy_b
print(sum)
mul = numpy_a * numpy_b
print(mul)

[1, 2, 3, 4, 4, 5, 6, 7]
[1 2 3 4]
[4 5 6 7]
[ 5  7  9 11]
[ 4 10 18 28]


In [29]:
myList = [4, 5, 6, 7]
myArr = np.array(myList)
print(myList)
print(myArr)

print(type(myList))
print(type(myArr))

# ndarray : 다차원 행렬 구조를 지원하는 numpy의 핵심 클래스

[4, 5, 6, 7]
[4 5 6 7]
<class 'list'>
<class 'numpy.ndarray'>


In [30]:
np.array([ [1,2,3],
           [4,5,6],
           [7,8,9] ])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# myList는 다른 변수에 할당한 값을 바꿔도 기존 변수에 저장된 값은 바뀌지 않지만,
# myArr은 다른 변수에 할당한 값을 바꿔주면 기존 변수도 바뀌는 것을 알 수 있다.

'''

리스트는 원본이 안바뀐다. 변경을 하게되면 기존의 것을 카피해놓고 새롭게 생성한 뷰를
쓰는 것이다.

반면에 nd배열은 데이터를 변경하면 원본뷰가 수정된다.

이것이 메모리상에서의 리스트와 nd배열의 가장 큰 차이점이다.

-->
메모리 효율성과 연관되는 부분이 발생한다.
'''


myList_sub = myList[1:3]
print(myList_sub)
myArr_sub = myArr[1:3]
print(myArr_sub)

myList_sub[0] = -5
print(myList_sub)
myArr_sub[0] = -5
print(myArr_sub)

print('=' * 40)

print(myList)
print(myArr)

[5, 6]
[-5  6]
[-5, 6]
[-5  6]
[4, 5, 6, 7]
[ 4 -5  6  7]


#### random 모듈의 난수 생성

In [66]:
a = np.random.rand(5)
print(a)
print(type(a))

b = np.random.randint(1, 10, 5) # 1부터 9 사이의 정수 5개 추출
print(b)
print(type(b))

c = np.random.randn(10) ## randn은 정규분포에 해당하는 값을 가져온다.
# randn값은 머신이 학습하기 좋은 데이터이다.
print(c)
print(type(c))

d = np.random.randn(3,5) # 3행 5열의 난수값을 생성한다.
print(d)

e = np.random.randint(1, 10, (3,5)) # 3행 5열의 정수값 생성
print(e)

[0.78713214 0.10680494 0.48644643 0.40698553 0.54812997]
<class 'numpy.ndarray'>
[2 9 6 2 7]
<class 'numpy.ndarray'>
[ 0.50197085  0.64456815  0.83109538  0.18540648 -1.07293777  1.97506425
 -1.29312778 -0.83331647  1.06291233  1.1314089 ]
<class 'numpy.ndarray'>
[[ 0.18668922 -0.71792847  0.47857931  0.66356919 -1.35387531]
 [ 0.69930684  0.26791885 -0.22138394  0.00270664  0.27282943]
 [-1.00995884 -0.12500446  1.1509325   0.13223056  0.22708121]]
[[9 6 4 7 7]
 [6 7 5 5 1]
 [9 3 1 1 5]]


### 2. np배열의 초기화
    zeros(),ones(), arange()..함수를 이용해서 배열 생성과 동시에 특정한 값으로
    초기화 할 수 있다

In [85]:
# 실수형으로 만들어진다. 
az = np.zeros(10)
print(az)

#
ao= np.ones(10)
print(ao)

#3. eye
ae = np.eye(3)
print(ae)
ae1 = np.eye(5)
print(ae1)

#4. arange()

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 10, 2))

print('=' * 40)

# 5. zeros와 ones로 다른 값도 만들기
ao= np.ones(10) * 7
print(ao)

print(np.zeros(10) + 11)

af = np.full((7, 5), 23) ## 23으로 7,5행렬을 모두 채운다.
print(af)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0 1 2]
[3 4 5 6]
[3 5 7 9]
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
[11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
[[23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]]


#### np배열과 리스트의 차이점
    1. np배열은 원본을 바로 바꿈으로써 메모리 효율성이 뛰어나다
    2. 리스트는 여러가지 자료형이 원소로 올수 있지만
       np배열은 한가지 자료형만 원소로 쓰일수 있다

In [92]:
L = [1,2, 3.9,'4', 'KB']
print(L)
print(type (L))

AL = np.array(L)
print(AL) # 한가지 자료형만 원소로 올 수 있으므로 가장 큰 데이터 타입인 문자로 변환된다.
print(type(AL))

[1, 2, 3.9, '4', 'KB']
<class 'list'>
['1' '2' '3.9' '4' 'KB']
<class 'numpy.ndarray'>


In [101]:
A2 = np.array([1,6,3,9.2])
print(A2) # 전부 다 실수형으로 변환된다.
print(type(A2))

A3 = np.array([1,2,3,4], dtype = 'float')
print(A3)

A4 = np.array([1,2,3,4], dtype = np.float64)
print(A4)

print(A4.ndim)
print(A4.shape)
print(A4.size)

[1.  6.  3.  9.2]
<class 'numpy.ndarray'>
[1. 2. 3. 4.]
[1. 2. 3. 4.]
1
(4,)
4


### 3. Numpy 배열에서 사용되는 함수, 속성
     * ndim  
     * shape
     * size
     * dtype
     * T  ==> 3X5행렬을 5X3으로 바꾼다. 행과 열을 바꾼다. T = > transpose
     
     reshape() type() astype()

In [107]:
import sys
arr = np.array([1,2,3,4]) ## dtype = np.int32로 고정되어 있다.
arr_f = np.array([1,2,3,4], dtype = np.int64)


print(sys.getsizeof(arr))
print(sys.getsizeof(arr_f))

# int32와 64는 밑과 같지 메모리를 차지하는 공간이 다르다.

120
136


In [110]:
arr1 = np.array([[1.0, 2, 3 ],
                 [4, 5, 6]], dtype = np.int32)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
#함수사용,,,,,,,,
print(type(arr1))
print(np.ndim(arr1))
print(np.shape(arr1))

print('*' * 30)

print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

print(arr1.dtype)

print('*' * 30)

#ndarray안에 들어있는 모든 요소들의 타입을 한방에 바꿔버리는 기능... astype
arr1_1 = arr1.astype(np.float32)                   
print(arr1_1.dtype)

print('*' * 30)

arr_r = np.arange(32).reshape(4,8)
arr_r

<class 'numpy.ndarray'>
2
(2, 3)
******************************
2
(2, 3)
6
int32
******************************
float32
******************************


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

### 4. Numpy Indexing, Slicing

파이썬에서 사용하던 인덱스, 슬라이싱과 동일

#### Indexing

`1차원 인덱싱`

In [150]:
arr1 = np.array([1,2,3,4,5])
arr1

arr1[2] # 3
arr1[-1] # 5
# arr1.[6] # error

arr1[:2] #슬라이싱 가능
print(arr1[-4:-1]) # [2 3 4]
print(arr1[::-1])

[2 3 4]
[5 4 3 2 1]


#### 조건 인덱싱

In [151]:
np.random.seed(0)

arr1 = np.random.randn(4,4)
arr1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [154]:
#1. 논리연산자를 사용해서 값을 받아옴
print(arr1 < 0) # 불린으로 나옴
print(arr1[arr1<0]) # 0보다 작은 값을 추출

[[False False False False]
 [False  True False  True]
 [ True False False False]
 [False False False False]]
[-0.97727788 -0.15135721 -0.10321885]


In [155]:
arr1[arr1<0] = 0 # ndarray는 원본이 바뀐다.
arr1

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

`2차원 인덱싱과 reshape  
 reshape는 변환전과 후의 행과 열 곱한 수가 동일해야 한다
`

`2차원 배열 슬라이싱과 reshape`

In [161]:
arr2 = np.arange(32).reshape(4, -1)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [165]:
arr2[:, 1:3]

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26]])

In [166]:
arr2[-1:, 1:3]

array([[25, 26]])

In [164]:
arr2[:, np.arange(1, 3)]

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26]])

### 5. 정렬

np.sort(arr)

In [179]:
arr3 = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 9, 10])

In [180]:
np.sort(arr3)

array([ 1,  2,  3,  4,  5,  6,  8,  8,  9, 10, 10])

In [181]:
arr3

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  9, 10])

`하지만 이 값들은 유지되지 않습니다.
`

In [189]:
# arr3 = np.sort(arr3)

In [175]:
# arr3

array([ 1,  2,  3,  4,  5,  6,  8,  8,  9, 10, 10])

`같은 변수로 할당해주면 된다.
`

`
데이터분석은 대부분 원본 데이터를 가지고 작업을 하는 것이다.
원본 데이터가 손상된다면 문제가 생길 수 있기 때문에 arr3.sort()처럼 바로 바뀌지 않도록 하기 위해서
위와 같이 설정해놓은 것이다.
실제 작업할 때는 np.sort()를 사용하는 것이 데이터 손상을 막기에는 좋다.
`

In [183]:
arr3.sort()
arr3 # 이런식으로 sort하게되면 값이 유지된다.

array([ 1,  2,  3,  4,  5,  6,  8,  8,  9, 10, 10])

In [188]:
print(type(np.sort(arr3)))
print(type(arr3.sort()))

<class 'numpy.ndarray'>
<class 'NoneType'>


#### N차원 정렬

In [191]:
arr2d = np.array([[5,6,7,8], 
                  [4,3,2,1],
                  [10, 9, 12, 11]])

arr2d.shape
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

`
열방향 정렬 = > axis = 1
행방향 정렬 = > axis = 0
axis만 쓰고 값을 할당하지 않으면 디폴트값 0
`

In [196]:
np.sort(arr2d, axis=1) # 열으로 정렬


array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [197]:
np.sort(arr2d, axis=0) # 행으로 정렬

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])