### 1. 연산

행렬의 사칙연산  

딥러닝, 머신러닝에서 사용하면 조금 더 고급스럼 용어로 바꾸면  
**Element Wise 연산**이라 한다.  

이것 외에도 다른 연산이 하나 더 있는데 **내적곱** 있다.

#### Element Wise

원소간의 연산  
행열에서 같은 위치에 있는 원소들끼리 사칙연산을 진행

In [2]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [3]:
x+y

array([[ 6,  8],
       [10, 12]])

In [6]:
x - y

array([[-4, -4],
       [-4, -4]])

In [4]:
x * y

array([[ 5, 12],
       [21, 32]])

In [5]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

#### Broadcsting

In [7]:
x * 100

array([[100, 200],
       [300, 400]])

In [8]:
x - 100

array([[-99, -98],
       [-97, -96]])

In [9]:
np.sqrt(x) # x값 전체에 루트를 씌운 꼴

# 이것 또한 broadcast의 한 종류이다.

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

`Shape이 안맞는 경우를 한번 보고 간다.
 당연히 에러난다
`

In [12]:
x = np.array([[1, 2, 3], [3, 4, 5]]) # 2X3
y = np.array([[5, 6], [7, 8]]) # 2X2
# x/y # shape이 다르기에 element wise가 안된다.


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

#### 내적곱(dot product)

In [14]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [16]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [17]:
print(arr1 @ arr2)

[[19 22]
 [43 50]]


In [18]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

### 통계함수
    sum, mean, min, max, argmin, argmax, cumsum

In [20]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### sum

arr.sum()  
np.sum(arr)  

두 함수 모두 리턴값이 있고 동작이 완전히 같다  
사용하기 편한걸 사용하면 된다.

In [28]:
arr.sum()

array([10, 26, 42])

In [30]:
print(np.sum(arr, axis = 1))
print(arr.sum(axis = 1))

[10 26 42]
[10 26 42]


In [31]:
print(np.sum(arr, axis = 0))
print(arr.sum(axis = 0))

[15 18 21 24]
[15 18 21 24]


#### mean

In [34]:
arr.mean()

6.5

#### min, max

In [35]:
arr.min()

1

In [25]:
arr.max()

12

#### std, var (표준편차와 분산)

분산은 데이타가 펴져있는 정도를 수치화 한것  
표준편차는 분산의 제곱근  

두개를 거의 비슷한 개념으로 보면 되고  
스케일에 약간의 차이가 있다  

머신러닝에서는 분산에 대한 개념이 중요하게 작용한다.



In [36]:
arr.var()

11.916666666666666

In [41]:
print(np.sqrt(arr.var()))
print(arr.std())

3.452052529534663
3.452052529534663
